name: Knative

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build image
      uses: docker://docker.io/buildpacksio/pack:0.29.0
      with:
        args: build test_build --path sample --builder paketo-buildpacks/builder:base