name: Knative

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'sample'
        tag: '1.0.0'
        path: 'sample/'
        builder: 'paketobuildpacks/builder:base'